# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(330, 158)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.valor_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_2.setObjectName("valor_2")
        self.gridLayout.addWidget(self.valor_2, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 2, 1, 1)
        self.dinheiro_1 = QtWidgets.QComboBox(self.centralwidget)
        self.dinheiro_1.setObjectName("dinheiro_1")
        self.gridLayout.addWidget(self.dinheiro_1, 1, 0, 1, 2)
        self.convert = QtWidgets.QPushButton(self.centralwidget)
        self.convert.setObjectName("convert")
        self.gridLayout.addWidget(self.convert, 3, 0, 1, 4)
        self.atualizar = QtWidgets.QPushButton(self.centralwidget)
        self.atualizar.setObjectName("atualizar")
        self.gridLayout.addWidget(self.atualizar, 0, 0, 1, 1)
        self.cronometro = QtWidgets.QLabel(self.centralwidget)
        self.cronometro.setText("")
        self.cronometro.setObjectName("cronometro")
        self.gridLayout.addWidget(self.cronometro, 0, 1, 1, 1)
        self.valor_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_1.setObjectName("valor_1")
        self.gridLayout.addWidget(self.valor_1, 2, 0, 1, 2)
        self.dinheiro_2 = QtWidgets.QComboBox(self.centralwidget)
        self.dinheiro_2.setObjectName("dinheiro_2")
        self.gridLayout.addWidget(self.dinheiro_2, 1, 3, 1, 1)
        self.data = QtWidgets.QLabel(self.centralwidget)
        self.data.setText("")
        self.data.setObjectName("data")
        self.gridLayout.addWidget(self.data, 0, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Converter Moedas"))
        self.label.setText(_translate("MainWindow", "  ->"))
        self.convert.setText(_translate("MainWindow", "Converte"))
        self.atualizar.setText(_translate("MainWindow", "Att"))
